version: '3.7'

services:
  api-gateway:
    image: elenadejanovic/api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - user-service
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  currency-conversion:
    image: elenadejanovic/currency-conversion:1.0.0
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  currency-exchange:
    image: elenadejanovic/currency-exchange:1.0.0
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka     
      
  naming-server:
    image: elenadejanovic/naming-server:0.0.1
    build:
      context: ./namingServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - currency-network

  user-service:
    image: elenadejanovic/user-service:1.0.0
    ports:
      - "8770:8770"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
 
networks:
  currency-network: