version: '3.7'

name: agilne-2024-elena-dejanovic
services:

  bank-account:
    image: elenadejanovic/bank-account:latest
    build:
      context: ./bank-account
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  currency-conversion:
    image: elenadejanovic/currency-conversion:latest
    build:
      context: ./currency-conversion
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  currency-exchange:
    image: elenadejanovic/currency-exchange:latest
    build:
      context: ./currency-exchange
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  naming-server:
    image: elenadejanovic/naming-server:latest
    build:
      context: ./namingServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - currency-network

  users-service:
    image: elenadejanovic/user-service:latest
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - "8770:8770"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  api-gateway:
    image: elenadejanovic/api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - users-service
      - bank-account
      - currency-exchange
      - currency-conversion
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
networks:
  currency-network: